function xp = sym_EoM_discrete_RDS(in1,in2)
%sym_EoM_discrete_RDS
%    XP = sym_EoM_discrete_RDS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Nov-2023 12:43:02

u11 = in2(1,:);
u12 = in2(2,:);
u13 = in2(3,:);
u21 = in2(4,:);
u22 = in2(5,:);
u23 = in2(6,:);
u24 = in2(7,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
t2 = u11.*x1;
t3 = u12.*x2;
t4 = u13.*x3;
t5 = u11.^2;
t6 = u12.^2;
t7 = u13.^2;
t8 = t2+t3+t4;
t9 = t5+t6+t7;
t10 = sqrt(t9);
t11 = 1.0./t10;
t12 = t10.*7.07125314117414e+3;
t13 = -t12;
t14 = t8.*t11.*1.57297407539752e+3;
t15 = t13+t14+7.311756864837817e+3;
mt1 = [x1+u21.*u23.*1.635e-1-u22.*u24.*1.635e-1;x2-u21.*u22.*1.635e-1-u23.*u24.*1.635e-1-t11.*t15.*u12.*1.454333934431101e-4];
mt2 = [x3+u22.^2.*1.635e-1+u23.^2.*1.635e-1-t11.*t15.*u13.*1.454333934431101e-4-8.175e-2];
xp = [mt1;mt2];
