function out1 = A_linearModel_UBsensor_LSS_4_4(t,in2,in3)
%A_linearModel_UBsensor_LSS_4_4
%    OUT1 = A_linearModel_UBsensor_LSS_4_4(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 13:50:56

out1 = 1.0;
