function out1 = A_linearModel_UBsensor_LSS_8_12(t,in2,in3)
%A_linearModel_UBsensor_LSS_8_12
%    OUT1 = A_linearModel_UBsensor_LSS_8_12(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 13:51:43

out1 = 1.0./1.2e+2;
