function out1 = A_linearModel_UBsensor_LSS_1_1(t,in2,in3)
%A_linearModel_UBsensor_LSS_1_1
%    OUT1 = A_linearModel_UBsensor_LSS_1_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    04-Sep-2023 13:14:11

out1 = 0.0;
