function out1 = A_linearModel_UBsensor_LSS_10_10(t,in2,in3)
%A_linearModel_UBsensor_LSS_10_10
%    OUT1 = A_linearModel_UBsensor_LSS_10_10(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 13:51:44

out1 = 1.0;
