function out1 = A_linearModel_UBsensor_LSS_2_1(t,in2,in3)
%A_linearModel_UBsensor_LSS_2_1
%    OUT1 = A_linearModel_UBsensor_LSS_2_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Aug-2023 13:50:49

out1 = 0.0;
